CREATE TABLE trade_post (
                            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            title VARCHAR(100) NOT NULL,
                            price BIGINT NOT NULL CHECK (price >= 0),
                            seller_name VARCHAR(30) NOT NULL,
                            description VARCHAR(1000) NOT NULL
);