CREATE TABLE trade_request (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    post_id BIGINT NOT NULL REFERENCES trade_post(id),
    buyer_id BIGINT NOT NULL REFERENCES member_account(id),
    seller_id BIGINT NOT NULL REFERENCES member_account(id),
    title VARCHAR(100) NOT NULL,
    price BIGINT NOT NULL CHECK (price >= 0),
    status VARCHAR(20) NOT NULL CHECK (status IN ('REQUESTED', 'RESERVED', 'COMPLETED', 'CANCELLED', 'REJECTED')),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_trade_request_participants CHECK (buyer_id <> seller_id)
);
CREATE INDEX idx_trade_request_post_status ON trade_request(post_id, status);
CREATE INDEX idx_trade_request_buyer ON trade_request(buyer_id, id DESC);
CREATE INDEX idx_trade_request_seller ON trade_request(seller_id, id DESC);
